gdjs.projectData = {
  firstLayout: "",
  gdVersion: { build: 99, major: 4, minor: 0, revision: 0 },
  properties: {
    adaptGameResolutionAtRuntime: true,
    folderProject: false,
    orientation: "portrait",
    packageName: "com.example.gamename",
    projectUuid: "37c6ca23-3a22-4fa3-b8a5-138fc9ae7b5a",
    scaleMode: "linear",
    sizeOnStartupMode: "",
    useExternalSourceFiles: false,
    version: "1.0.0",
    name: "Geometry Monster",
    author: "Jamal",
    windowWidth: 960,
    windowHeight: 600,
    latestCompilationDirectory: "C:\\Users\\Jamal\\Downloads\\MyGame",
    maxFPS: 60,
    minFPS: 20,
    verticalSync: false,
    platformSpecificAssets: {},
    loadingScreen: { showGDevelopSplash: true },
    extensionProperties: [],
    platforms: [{ name: "GDevelop JS platform" }],
    currentPlatform: "GDevelop JS platform",
  },
  resources: {
    resources: [
      {
        alwaysLoaded: false,
        file: "life-3.png",
        kind: "image",
        metadata: "",
        name: "life-3.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "life-2.png",
        kind: "image",
        metadata: "",
        name: "life-2.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "life-1.png",
        kind: "image",
        metadata: "",
        name: "life-1.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "life-0.png",
        kind: "image",
        metadata: "",
        name: "life-0.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "game-over.png",
        kind: "image",
        metadata: "",
        name: "game-over.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "btn-try-again-hover.png",
        kind: "image",
        metadata: "",
        name: "btn-try-again-hover.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "btn-try-again-hover2.png",
        kind: "image",
        metadata: "",
        name: "btn-try-again-hover2.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "btn-try-again-normal.png",
        kind: "image",
        metadata: "",
        name: "btn-try-again-normal.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "btn-try-again-pressed.png",
        kind: "image",
        metadata: "",
        name: "btn-try-again-pressed.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "btn-main-menu-hover.png",
        kind: "image",
        metadata: "",
        name: "btn-main-menu-hover.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "btn-main-menu-hover2.png",
        kind: "image",
        metadata: "",
        name: "btn-main-menu-hover2.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "btn-main-menu-normal.png",
        kind: "image",
        metadata: "",
        name: "btn-main-menu-normal.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "btn-main-menu-pressed.png",
        kind: "image",
        metadata: "",
        name: "btn-main-menu-pressed.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "btn-start-normal.png",
        kind: "image",
        metadata: "",
        name: "btn-start-normal.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "btn-start-hover.png",
        kind: "image",
        metadata: "",
        name: "btn-start-hover.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "btn-start-pressed.png",
        kind: "image",
        metadata: "",
        name: "btn-start-pressed.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "btn-start-normal2.png",
        kind: "image",
        metadata: "",
        name: "btn-start-normal2.png",
        smoothed: true,
        userAdded: true,
      },
      {
        file: "wrong.mp3",
        kind: "audio",
        metadata: "",
        name: "wrong.mp3",
        preloadAsMusic: false,
        preloadAsSound: false,
        userAdded: true,
      },
      {
        file: "right.mp3",
        kind: "audio",
        metadata: "",
        name: "right.mp3",
        preloadAsMusic: false,
        preloadAsSound: false,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "congratulations-png-22059.png",
        kind: "image",
        metadata: "",
        name: "congratulations-png-22059.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "kisspng-desktop-wallpaper-sorry-smiley-sorry-5ad70bb44f0a31.8298399215240426763238.png",
        kind: "image",
        metadata: "",
        name: "kisspng-desktop-wallpaper-sorry-smiley-sorry-5ad70bb44f0a31.8298399215240426763238.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "1.png",
        kind: "image",
        metadata: "",
        name: "1.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_attack0.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_attack0.png",
        smoothed: true,
        userAdded: true,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_attack1.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_attack1.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_attack2.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_attack2.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_attackKick.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_attackKick.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_behindBack.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_behindBack.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_cheer0.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_cheer0.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_cheer1.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_cheer1.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_walk0.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_walk0.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_walk1.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_walk1.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_walk2.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_walk2.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_walk3.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_walk3.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_walk4.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_walk4.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_walk5.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_walk5.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_walk6.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_walk6.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_walk7.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_walk7.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "MonsterIdle-1.png",
        kind: "image",
        metadata: "",
        name: "MonsterIdle-1.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "MonsterIdle-2.png",
        kind: "image",
        metadata: "",
        name: "MonsterIdle-2.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "MonsterIdle-3.png",
        kind: "image",
        metadata: "",
        name: "MonsterIdle-3.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "MonsterIdle-4.png",
        kind: "image",
        metadata: "",
        name: "MonsterIdle-4.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "MonsterIdle-5.png",
        kind: "image",
        metadata: "",
        name: "MonsterIdle-5.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "MonsterIdle-6.png",
        kind: "image",
        metadata: "",
        name: "MonsterIdle-6.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "MonsterIdle-7.png",
        kind: "image",
        metadata: "",
        name: "MonsterIdle-7.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "MonsterIdle-8.png",
        kind: "image",
        metadata: "",
        name: "MonsterIdle-8.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "MonsterIdle-9.png",
        kind: "image",
        metadata: "",
        name: "MonsterIdle-9.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "character_femalePerson_duck.png",
        kind: "image",
        metadata: "",
        name: "character_femalePerson_duck.png",
        smoothed: true,
        userAdded: false,
      },
      {
        alwaysLoaded: false,
        file: "Math Game.png",
        kind: "image",
        metadata: "",
        name: "Math Game.png",
        smoothed: true,
        userAdded: true,
      },
    ],
    resourceFolders: [],
  },
  objects: [],
  objectsGroups: [],
  variables: [],
  layouts: [
    {
      b: 33,
      disableInputWhenNotFocused: true,
      mangledName: "Home",
      name: "Home",
      oglFOV: 90.0,
      oglZFar: 500.0,
      oglZNear: 1.0,
      r: 86,
      standardSortMethod: true,
      stopSoundsOnStartup: true,
      title: "",
      v: 9,
      uiSettings: {
        grid: false,
        gridB: 255,
        gridG: 180,
        gridHeight: 32.0,
        gridOffsetX: 0.0,
        gridOffsetY: 0.0,
        gridR: 158,
        gridType: "rectangular",
        gridWidth: 32.0,
        snap: true,
        windowMask: false,
        zoomFactor: 0.3799999999999995,
      },
      objectsGroups: [],
      variables: [{ name: "Divider", type: "number", value: 2.0 }],
      instances: [
        {
          angle: 0.0,
          customSize: false,
          height: 0.0,
          layer: "",
          locked: false,
          name: "Title",
          persistentUuid: "7c90ddd9-6dcc-4107-a5bf-b58a7794a03d",
          width: 0.0,
          x: 216.0,
          y: 73.0,
          zOrder: 1,
          numberProperties: [],
          stringProperties: [],
          initialVariables: [],
        },
        {
          angle: 0.0,
          customSize: false,
          height: 0.0,
          layer: "",
          locked: false,
          name: "BtnStart",
          persistentUuid: "1b54bc4e-5a53-407e-a8b4-7cfe793d0e23",
          width: 0.0,
          x: 368.0,
          y: 360.0,
          zOrder: 2,
          numberProperties: [],
          stringProperties: [],
          initialVariables: [],
        },
      ],
      objects: [
        {
          name: "Title",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [
            {
              name: "SineMovement",
              type: "SineMovement::SineMovement",
              HorizontalSpeed: 60.0,
              VerticalSpeed: 60.0,
              HorizontalDistance: 20.0,
              VerticalDistance: 10.0,
              CenterPointX: 0.0,
              CenterPointY: 0.0,
              SineProgressX: 0.0,
              SineProgressY: 0.0,
            },
          ],
          animations: [
            {
              name: "HungryDude",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "Math Game.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "BtnStart",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "StartNormal",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "btn-start-normal2.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "StartHover",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "btn-start-hover.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "StartPressed",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "btn-start-pressed.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
      events: [],
      layers: [
        {
          ambientLightColorB: 0,
          ambientLightColorG: 196608,
          ambientLightColorR: 0,
          followBaseLayerCamera: false,
          isLightingLayer: false,
          name: "",
          visibility: true,
          cameras: [
            {
              defaultSize: true,
              defaultViewport: true,
              height: 0.0,
              viewportBottom: 1.0,
              viewportLeft: 0.0,
              viewportRight: 1.0,
              viewportTop: 0.0,
              width: 0.0,
            },
          ],
          effects: [],
        },
      ],
      behaviorsSharedData: [
        { name: "SineMovement", type: "SineMovement::SineMovement" },
      ],
    },
    {
      b: 50,
      disableInputWhenNotFocused: true,
      mangledName: "Level1",
      name: "Level1",
      oglFOV: 90.0,
      oglZFar: 500.0,
      oglZNear: 1.0,
      r: 72,
      standardSortMethod: true,
      stopSoundsOnStartup: true,
      title: "",
      v: 0,
      uiSettings: {
        grid: false,
        gridB: 255,
        gridG: 180,
        gridHeight: 32.0,
        gridOffsetX: 0.0,
        gridOffsetY: 0.0,
        gridR: 158,
        gridType: "rectangular",
        gridWidth: 32.0,
        snap: true,
        windowMask: false,
        zoomFactor: 0.5799999999999996,
      },
      objectsGroups: [],
      variables: [
        { name: "Divider", type: "number", value: 2.0 },
        { name: "SuccessScore", type: "number", value: 5.0 },
        { name: "Score", type: "number", value: 0.0 },
        { name: "TimeLimit", type: "number", value: 25.0 },
      ],
      instances: [
        {
          angle: 0.0,
          customSize: true,
          height: 193.0,
          layer: "",
          locked: false,
          name: "Monster",
          persistentUuid: "1e06cb6b-a809-46a9-b5cd-40f55cd7993c",
          width: 151.0,
          x: 379.0,
          y: 320.0,
          zOrder: 1,
          numberProperties: [],
          stringProperties: [],
          initialVariables: [],
        },
        {
          angle: 0.0,
          customSize: false,
          height: 0.0,
          layer: "",
          locked: false,
          name: "Score",
          persistentUuid: "74fc738c-bd6c-450f-9d29-cbd000d4bbce",
          width: 0.0,
          x: 27.0,
          y: 20.0,
          zOrder: 2,
          numberProperties: [],
          stringProperties: [],
          initialVariables: [],
        },
        {
          angle: 0.0,
          customSize: false,
          height: 0.0,
          layer: "",
          locked: false,
          name: "Life",
          persistentUuid: "24ac2dfb-5a48-405e-b61f-3a3b0afd70eb",
          width: 0.0,
          x: 792.0,
          y: 29.0,
          zOrder: 3,
          numberProperties: [],
          stringProperties: [],
          initialVariables: [],
        },
        {
          angle: 0.0,
          customSize: false,
          height: 0.0,
          layer: "",
          locked: false,
          name: "GameOver",
          persistentUuid: "0de4f860-edc2-4a72-aa5f-3d744e0ad65f",
          width: 0.0,
          x: 252.0,
          y: 54.0,
          zOrder: 4,
          numberProperties: [],
          stringProperties: [],
          initialVariables: [],
        },
        {
          angle: 0.0,
          customSize: true,
          height: 128.0,
          layer: "",
          locked: false,
          name: "BtnTryAgain",
          persistentUuid: "06522629-14bb-4dd6-9973-9f81f73eb59f",
          width: 130.0,
          x: 745.0,
          y: 91.0,
          zOrder: 5,
          numberProperties: [],
          stringProperties: [],
          initialVariables: [],
        },
        {
          angle: 0.0,
          customSize: true,
          height: 121.0,
          layer: "",
          locked: false,
          name: "BtnHome",
          persistentUuid: "b0103361-ea79-4323-b32e-72714cd00a50",
          width: 116.0,
          x: 53.0,
          y: 88.0,
          zOrder: 6,
          numberProperties: [],
          stringProperties: [],
          initialVariables: [],
        },
        {
          angle: 0.0,
          customSize: true,
          height: 166.0,
          layer: "",
          locked: false,
          name: "Congrats",
          persistentUuid: "3ef3d114-61c2-406b-b67d-ee11f062321c",
          width: 604.0,
          x: 151.0,
          y: 415.0,
          zOrder: 7,
          numberProperties: [],
          stringProperties: [],
          initialVariables: [],
        },
        {
          angle: 0.0,
          customSize: true,
          height: 161.0,
          layer: "",
          locked: false,
          name: "Sorry",
          persistentUuid: "b9fbe18f-26be-470a-8882-b610e9b62580",
          width: 178.0,
          x: 545.0,
          y: 413.0,
          zOrder: 8,
          numberProperties: [],
          stringProperties: [],
          initialVariables: [],
        },
      ],
      objects: [
        {
          name: "Monster",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [
            {
              name: "Flash",
              type: "Flash::Flash",
              HalfPeriodTime: 0.1,
              IsFlashing: false,
              FlashDuration: 0.0,
            },
            {
              name: "Health",
              type: "Health::Health",
              Health: 3.0,
              DamageCooldown: 0.8,
              MaxHealth: 3.0,
              IsJustDamaged: false,
              CooldownActive: false,
            },
            {
              name: "StayOnScreen",
              type: "StayOnScreen::StayOnScreen",
              MarginTop: 0.0,
              MarginBottom: 0.0,
              MarginLeft: 0.0,
              MarginRight: 133.0,
            },
          ],
          animations: [
            {
              name: "MonsterIdle",
              useMultipleDirections: false,
              directions: [
                {
                  looping: true,
                  timeBetweenFrames: 0.10000000149011612,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "MonsterIdle-1.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "MonsterIdle-2.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "MonsterIdle-3.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "MonsterIdle-4.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "MonsterIdle-5.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "MonsterIdle-6.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "MonsterIdle-7.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "MonsterIdle-8.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "MonsterIdle-9.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "Dead",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.07999999821186066,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "character_femalePerson_duck.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Shape1",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "NewObject1",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "geometry1.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Shape2",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "NewObject2",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "geometry2.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Shape3",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "NewObject3",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "geometry3.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Shape4",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "NewObject4",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "geometry4.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          bold: true,
          italic: false,
          name: "Score",
          smoothed: true,
          tags: "",
          type: "TextObject::Text",
          underlined: false,
          variables: [],
          behaviors: [],
          string: "Score",
          font: "",
          characterSize: 30.0,
          color: { b: 0, g: 249, r: 255 },
        },
        {
          name: "Obstacle",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "Obstacle",
              useMultipleDirections: false,
              directions: [
                {
                  looping: true,
                  timeBetweenFrames: 0.10000000149011612,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "bomb1.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "bomb2.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Life",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "Life3",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "life-3.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "Life2",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "life-2.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "Life1",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "life-1.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "Life0",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "life-0.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "GameOver",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "GameOver",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "game-over.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "BtnTryAgain",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "TryAgainNormal",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "btn-try-again-normal.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "TryAgainHover",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "btn-try-again-hover2.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "TryAgainPressed",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "btn-try-again-pressed.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "BtnHome",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "HomeNormal",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "btn-main-menu-normal.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "HomeHover",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "btn-main-menu-hover2.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "HomePressed",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "btn-main-menu-pressed.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          additive: true,
          alphaParam: "Mutable",
          angleParam: "Mutable",
          blueParam: "Random",
          destroyWhenNoParticles: true,
          emissionEditionSimpleMode: true,
          emitterAngleA: 0.0,
          emitterAngleB: 360.0,
          emitterForceMax: 85.0,
          emitterForceMin: 45.0,
          emitterXDirection: 0.0,
          emitterYDirection: 1.0,
          emitterZDirection: 0.0,
          flow: 45.0,
          friction: 2.0,
          gravityEditionSimpleMode: true,
          greenParam: "Random",
          maxParticleNb: 10,
          name: "Shape1Explosion",
          particleAlpha1: 255.0,
          particleAlpha2: 255.0,
          particleAlphaRandomness1: 0.0,
          particleAlphaRandomness2: 0.0,
          particleAngle1: 0.0,
          particleAngle2: 40.0,
          particleAngleRandomness1: 0.0,
          particleAngleRandomness2: 0.0,
          particleBlue1: 255.0,
          particleBlue2: 255.0,
          particleEditionSimpleMode: true,
          particleGravityX: 0.0,
          particleGravityY: 0.0,
          particleGravityZ: 0.0,
          particleGreen1: 255.0,
          particleGreen2: 255.0,
          particleLifeTimeMax: 2.5,
          particleLifeTimeMin: 0.5,
          particleRed1: 255.0,
          particleRed2: 255.0,
          particleSize1: 100.0,
          particleSize2: 80.0,
          particleSizeRandomness1: 0.0,
          particleSizeRandomness2: 0.0,
          redParam: "Enabled",
          rendererParam1: 10.0,
          rendererParam2: 10.0,
          rendererType: "Quad",
          sizeParam: "Mutable",
          tags: "",
          tank: 5.0,
          textureParticleName: "geometry1.png",
          type: "ParticleSystem::ParticleEmitter",
          zoneRadius: 9.0,
          variables: [],
          behaviors: [],
        },
        {
          bold: true,
          italic: false,
          name: "Numbers",
          smoothed: true,
          tags: "",
          type: "TextObject::Text",
          underlined: false,
          variables: [
            { name: "numberContent", type: "string", value: "-1" },
            { name: "zeroMod", type: "number", value: 0.0 },
          ],
          behaviors: [],
          string: "dd",
          font: "",
          characterSize: 30.0,
          color: { b: 255, g: 255, r: 255 },
        },
        {
          name: "Congrats",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "congratulations-png-22059.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Sorry",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "",
              useMultipleDirections: false,
              directions: [
                {
                  looping: false,
                  timeBetweenFrames: 0.08,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image:
                        "kisspng-desktop-wallpaper-sorry-smiley-sorry-5ad70bb44f0a31.8298399215240426763238.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "NewObject",
          tags: "",
          type: "Sprite",
          updateIfNotVisible: false,
          variables: [],
          behaviors: [],
          animations: [
            {
              name: "",
              useMultipleDirections: false,
              directions: [
                {
                  looping: true,
                  timeBetweenFrames: 0.15000000596046449,
                  sprites: [
                    {
                      hasCustomCollisionMask: false,
                      image: "character_femalePerson_behindBack.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "character_femalePerson_cheer0.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                    {
                      hasCustomCollisionMask: false,
                      image: "character_femalePerson_cheer1.png",
                      points: [],
                      originPoint: { name: "origine", x: 0.0, y: 0.0 },
                      centerPoint: {
                        automatic: true,
                        name: "centre",
                        x: 0.0,
                        y: 0.0,
                      },
                      customCollisionMask: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
      events: [],
      layers: [
        {
          ambientLightColorB: 0,
          ambientLightColorG: 0,
          ambientLightColorR: 0,
          followBaseLayerCamera: false,
          isLightingLayer: false,
          name: "",
          visibility: true,
          cameras: [
            {
              defaultSize: true,
              defaultViewport: true,
              height: 0.0,
              viewportBottom: 1.0,
              viewportLeft: 0.0,
              viewportRight: 1.0,
              viewportTop: 0.0,
              width: 0.0,
            },
          ],
          effects: [],
        },
      ],
      behaviorsSharedData: [
        { name: "Flash", type: "Flash::Flash" },
        { name: "Health", type: "Health::Health" },
        { name: "StayOnScreen", type: "StayOnScreen::StayOnScreen" },
      ],
    },
  ],
  externalEvents: [],
  eventsFunctionsExtensions: [],
  externalLayouts: [],
  externalSourceFiles: [],
};
gdjs.runtimeGameOptions = {};
